### ISSUE TITLE
bug: missing `content-type` header in prometheus metrics response

### ISSUE THREAD

**Issue by 0x416e746f6e** [flashbots/rollup-boost#117]
Prometheus fails to scrape `rollup-boost` metrics due to error:

```
Error scraping target: non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target
```

^-- apparently, it wants to see the `content-type` header.

See also:  https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format

**Comment by 0x416e746f6e** [comment]
for workaround (until this issue is fixed), specify `fallback_scrape_protocol = "PrometheusText0.0.4"`.

e.g.:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rollup-boost
spec:
  fallbackScrapeProtocol: PrometheusText0.0.4

  # ...
```
